version: 2.1
jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.4.9-node-browsers-legacy
        environment:
          BUNDLER_VERSION: 1.17.3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout
      - run: bundle install --path vendor/bundle --clean --jobs 4 --retry 3
      - run: bundle exec rubocop
