version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.9-node-browsers-legacy
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    steps:
      - checkout
      - run:
          name: Run rubocop
          command: bundle exec rubocop
