version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.9
    working_directory: ~/rails-tutorial-modify
    steps:
      - checkout
      - run:
        name: run rubocop
        command: bundle exec rubocop
