version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.9
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7

    working_directory: ~/rails-tutorial-modify

    steps:
      - checkout
      - run:
        name: run rubocop
        command: bundle exec rubocop
