apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: demo
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
